spring:
  application:
    name: tikitaka
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            user-name-attribute: sub

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}
