CREATE TYPE "schedule_status" AS ENUM (
  'SCHEDULED',
  'OPEN',
  'CLOSED',
  'CANCELED'
);

CREATE TYPE "performance_genre" AS ENUM (
  'CONCERT',
  'MUSICAL',
  'PLAY',
  'CLASSICAL',
  'FESTIVAL',
  'FAN_MEETING'
);

CREATE TYPE "performance_region" AS ENUM (
  'SEOUL',
  'GYEONGGI',
  'INCHEON',
  'GANGWON',
  'CHUNGCHEONG',
  'JEOLLA',
  'GYEONGSANG',
  'BUSAN',
  'DAEGU',
  'DAEJEON',
  'GWANGJU',
  'ULSAN',
  'JEJU'
);

CREATE TYPE "seat_status" AS ENUM (
  'AVAILABLE',
  'HELD',
  'RESERVED'
);

CREATE TYPE "seat_grade" AS ENUM (
  'VIP',
  'R',
  'S',
  'A',
  'B'
);

CREATE TYPE "simulation_status" AS ENUM (
  'SCHEDULED',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'CANCELED'
);

CREATE TYPE "reservation_status" AS ENUM (
  'PENDING_PAYMENT',
  'CONFIRMED',
  'FAILED',
  'EXPIRED',
  'CANCELED'
);

CREATE TYPE "payment_status" AS ENUM (
  'REQUESTED',
  'SUCCESS',
  'FAILED',
  'CANCELED',
  'TIMEOUT'
);

CREATE TYPE "attempt_result" AS ENUM (
  'SUCCESS',
  'FAIL'
);

CREATE TYPE "attempt_failure_code" AS ENUM (
  'SEAT_HELD',
  'SEAT_RESERVED',
  'SOLD_OUT',
  'PAYMENT_TIMEOUT',
  'LOCK_TIMEOUT',
  'UNKNOWN'
);

CREATE TYPE "oauth_provider" AS ENUM (
  'GOOGLE',
  'LOCAL'
);

CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "email" varchar UNIQUE NOT NULL,
                         "password_hash" varchar,
                         "name" varchar NOT NULL,
                         "provider" oauth_provider NOT NULL,
                         "provider_id" varchar,
                         "created_at" timestamp NOT NULL,
                         "updated_at" timestamp NOT NULL,
                         "last_login_at" timestamp
);

CREATE TABLE "performances" (
                                "performance_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "title" varchar NOT NULL,
                                "artist" varchar NOT NULL,
                                "venue_name" varchar NOT NULL,
                                "region" performance_region NOT NULL,
                                "genre" performance_genre NOT NULL,
                                "description" text,
                                "poster_url" varchar,
                                "created_at" timestamp NOT NULL
);

CREATE TABLE "performance_schedules" (
                                         "schedule_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "performance_id" bigint NOT NULL,
                                         "performance_datetime" timestamp NOT NULL,
                                         "open_at" timestamp NOT NULL, -- 예매 오픈 시각(#75). 공연 오픈 스케줄러가 이 시각 기준으로 OPEN 전환
                                         "status" schedule_status NOT NULL
);

CREATE TABLE "sections" (
                            "section_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "schedule_id" bigint NOT NULL,
                            "name" varchar NOT NULL,
                            "total_seat_count" int NOT NULL,
                            "remaining_seat_count" int NOT NULL
);

CREATE TABLE "seats" (
                         "seat_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "section_id" bigint NOT NULL,
                         "row_name" varchar NOT NULL,
                         "seat_number" int NOT NULL,
                         "grade" seat_grade NOT NULL,
                         "price" int NOT NULL,
                         "status" seat_status NOT NULL,
                         "seat_score" int,
                         "priority_rank" int,
                         "version" bigint NOT NULL
);

CREATE TABLE "simulations" (
                               "simulation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" bigint NOT NULL,
                               "schedule_id" bigint NOT NULL,
                               "scheduled_start_time" timestamp NOT NULL,
                               "virtual_user_count" int NOT NULL,
                               "k6_script_path" varchar,
                               "k6_run_id" varchar,
                               "status" simulation_status NOT NULL,
                               "created_at" timestamp NOT NULL,
                               "started_at" timestamp,
                               "ended_at" timestamp
);

CREATE TABLE "reservations" (
                                "reservation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "user_id" bigint NOT NULL,
                                "simulation_id" bigint NOT NULL,
                                "schedule_id" bigint NOT NULL,
                                "selected_quantity" int NOT NULL,
                                "status" reservation_status NOT NULL,
                                "created_at" timestamp NOT NULL,
                                "confirmed_at" timestamp,
                                "expired_at" timestamp,
                                "canceled_at" timestamp
);

CREATE TABLE "reservation_seats" (
                                     "reservation_seat_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "reservation_id" bigint NOT NULL,
                                     "seat_id" bigint NOT NULL,
                                     "hold_started_at" timestamp,
                                     "hold_expires_at" timestamp,
                                     "confirmed_at" timestamp,
                                     "released_at" timestamp,
                                     "created_at" timestamp NOT NULL
);

CREATE TABLE "payments" (
                            "payment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "reservation_id" bigint NOT NULL,
                            "pg_transaction_id" varchar,
                            "status" payment_status NOT NULL,
                            "amount" int NOT NULL,
                            "requested_at" timestamp NOT NULL,
                            "completed_at" timestamp,
                            "failed_at" timestamp,
                            "failure_reason" varchar,
                            "created_at" timestamp NOT NULL
);

CREATE TABLE "simulation_attempt_logs" (
                                           "attempt_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "simulation_id" bigint NOT NULL,
                                           "reservation_id" bigint,
                                           "seat_id" bigint NOT NULL,
                                           "virtual_user_key" varchar,
                                           "vu_index" int,
                                           "iteration_no" int NOT NULL,
                                           "attempt_sequence" bigint NOT NULL,
                                           "result" attempt_result NOT NULL,
                                           "failure_code" attempt_failure_code,
                                           "request_sent_at" timestamp,
                                           "request_arrived_at" timestamp,
                                           "lock_acquired_at" timestamp,
                                           "seat_occupied_at" timestamp,
                                           "processed_at" timestamp,
                                           "response_time_ms" bigint,
                                           "lock_wait_time_ms" bigint,
                                           "time_diff_ms" bigint,
                                           "seat_status_at_request" seat_status,
                                           "seat_holder_reservation_seat_id" bigint,
                                           "log_message" text,
                                           "created_at" timestamp NOT NULL
);

CREATE TABLE "simulation_run_metrics" (
                                          "metric_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "simulation_id" bigint UNIQUE NOT NULL,
                                          "total_request_count" int NOT NULL,
                                          "success_count" int NOT NULL,
                                          "fail_count" int NOT NULL,
                                          "avg_response_time_ms" bigint,
                                          "min_response_time_ms" bigint,
                                          "max_response_time_ms" bigint,
                                          "p95_response_time_ms" bigint,
                                          "p99_response_time_ms" bigint,
                                          "http_req_failed_rate" decimal,
                                          "k6_summary_json" json,
                                          "created_at" timestamp NOT NULL
);

CREATE INDEX ON "users" ("email");

CREATE UNIQUE INDEX ON "users" ("provider", "provider_id");

CREATE INDEX ON "performances" ("genre");

CREATE INDEX ON "performances" ("region");

CREATE INDEX ON "performance_schedules" ("performance_id");

CREATE INDEX ON "performance_schedules" ("performance_datetime");

CREATE INDEX ON "performance_schedules" ("status");

CREATE INDEX ON "sections" ("schedule_id");

CREATE UNIQUE INDEX ON "seats" ("section_id", "row_name", "seat_number");

CREATE INDEX ON "seats" ("section_id", "status");

CREATE INDEX ON "seats" ("section_id", "priority_rank");

CREATE INDEX ON "simulations" ("user_id");

CREATE INDEX ON "simulations" ("schedule_id");

CREATE INDEX ON "simulations" ("status");

CREATE INDEX ON "simulations" ("scheduled_start_time");

CREATE INDEX ON "reservations" ("user_id");

CREATE INDEX ON "reservations" ("simulation_id");

CREATE INDEX ON "reservations" ("schedule_id");

CREATE INDEX ON "reservations" ("status");

CREATE INDEX ON "reservation_seats" ("reservation_id");

CREATE INDEX ON "reservation_seats" ("seat_id");

CREATE INDEX ON "reservation_seats" ("hold_expires_at");

CREATE INDEX ON "payments" ("reservation_id");

CREATE INDEX ON "payments" ("status");

CREATE INDEX ON "payments" ("pg_transaction_id");

CREATE INDEX ON "simulation_attempt_logs" ("simulation_id");

CREATE INDEX ON "simulation_attempt_logs" ("reservation_id");

CREATE INDEX ON "simulation_attempt_logs" ("seat_id");

CREATE INDEX ON "simulation_attempt_logs" ("result");

CREATE INDEX ON "simulation_attempt_logs" ("failure_code");

CREATE INDEX ON "simulation_attempt_logs" ("attempt_sequence");

ALTER TABLE "performance_schedules" ADD FOREIGN KEY ("performance_id") REFERENCES "performances" ("performance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sections" ADD FOREIGN KEY ("schedule_id") REFERENCES "performance_schedules" ("schedule_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seats" ADD FOREIGN KEY ("section_id") REFERENCES "sections" ("section_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulations" ADD FOREIGN KEY ("schedule_id") REFERENCES "performance_schedules" ("schedule_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("simulation_id") REFERENCES "simulations" ("simulation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("schedule_id") REFERENCES "performance_schedules" ("schedule_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservation_seats" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservation_seats" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("seat_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulation_attempt_logs" ADD FOREIGN KEY ("simulation_id") REFERENCES "simulations" ("simulation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulation_attempt_logs" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulation_attempt_logs" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("seat_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulation_attempt_logs" ADD FOREIGN KEY ("seat_holder_reservation_seat_id") REFERENCES "reservation_seats" ("reservation_seat_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "simulation_run_metrics" ADD FOREIGN KEY ("simulation_id") REFERENCES "simulations" ("simulation_id") DEFERRABLE INITIALLY IMMEDIATE;